config/routes.rb
Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:new, :index, :create, :show, :edit, :update] do
    resources :tools
    resources :categories, only: [:index]
  end

  namespace :admin do
    get "tools/new" => "tools#new"
    get "tools", as: :tools
    post "tools" => "tools#create"
  end

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validate :tool_assigned_to_non_admin_user

  belongs_to :user
  belongs_to :category

  def tool_assigned_to_non_admin_user
    # bad because for non-admin user user_id gets assigned after saving
    # for admin, user_id gets assigned in form, so before create method is called
    # as a result can't just validate on user's role but have to use attributes
    # of the tool trying to be created, i.e. self
    if self.user_id && User.find(self.user_id).role == "admin"
      errors.add(:user_id, "You must select a non-admin user.")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :tools
  has_many :sessions
  has_many :categories, through: :tools
  #
  # def password
  #   @password ||= Password.new(params[:password])
  # end

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "./public/404" unless current_admin?
  end

end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::BaseController

  def new
    @user = User.find(session[:user_id])
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      @user = User.find(params[:tool][:user_id])
      redirect_to user_path(@user.id)
    else
      flash[:error] = "You must select a non-admin user for this tool."
      redirect_to admin_tools_new_path
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :current_user
  helper_method :most_recent_tool

  before_action :reroute_other_user, only: [:edit, :update, :show]

  def current_admin?
    current_user && current_user.admin?
  end

  def reroute_other_user
    if params[:id].to_i != session[:user_id]
      @user = User.find(session[:user_id])
      render :file => "./public/404.html",  :status => 404
    end
  end

  def current_user
    # byebug
    # @user ||= Session.find_by(user_id: @user.id)
    @user ||= User.find(session[:user_id])
  end

  def most_recent_tool
    if session[:most_recent_tool_id].nil?
      nil
    else
      tool = Tool.find(session[:most_recent_tool_id])
      tool.name
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    @categories = @user.categories
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:sessions][:username])
    if @user && @user.authenticate(params[:sessions][:password])
      Session.create(user_id: @user.id)
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
    end
  end

  def destroy
    holder = Session.find_by(user_id: session[:user_id])
    holder.destroy
    session[:most_recent_tool_id] = nil
    session[:current_tool_count] = 0
    redirect_to login_path
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  helper_method :most_recent_tool

  def index
    @tools = Tool.all
  end

  def show
    @user = User.find(session[:user_id])
    @tool = Tool.find(params[:id])
  end

  def new
    @user = User.find(session[:user_id])
    @tool = Tool.new
  end

  def create
    session[:current_tool_count] = 0 if session[:most_recent_tool_id].nil?
    @tool = Tool.new(tool_params)
    if @tool.save
      user = User.find(session[:user_id])
      @tool.update_attribute :user_id, "#{user.id}"
      flash[:notice] = "Tool successfully created"
      session[:most_recent_tool_id] = @tool.id
      session[:current_tool_count] += 1
      redirect_to user_tool_path(user.id, @tool.id)
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @user = User.find(session[:user_id])
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update_attributes( tool_params )
      redirect_to tool_path
    else
      redirect_to edit_tool_path(@tool.id)
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Session.create(user_id: @user.id)
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
      flash[:notice] = "You have created an account."
    else
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    User.update(@user.id, user_params)
    flash[:notice] = "You have updated yourself."
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/tools/new.html.erb
<%= form_for [:admin, @tool] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.collection_select(:user_id, User.all, :id, :username) %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>

  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories of your tools</h1>

<% @categories.each do |category| %>
  <%= category.name %>: <% category.tools.each do |tool| %>
                        <%= tool.name %>
                        <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if Session.find_by(user_id: @user.id) %>
  <%= link_to "Logout", logout_path, method: "delete" %>
<% else %>
  <%= link_to "Login", login_path %>
<% end %>

<% flash.each do |key, value| %>
  <%= flash[key] %>
<% end %>

<p><strong>Newest tool:</strong> <%= most_recent_tool %></p>
<p><strong>Tools created this session:</strong> <%= session[:current_tool_count] %></p>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for [user, tool] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.collection_select(:category_id, Category.all, :id, :name) %>

  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<h1>Edit <%= @tool.name %></h1>

<%= render partial: "form", locals: {user: @user, tool: @tool} %>

app/views/tools/index.html.erb
<h1>All Tools</h1>

<% @tools.each do |tool| %>
  <p><%= link_to "#{tool.name}", tool_path(tool.id) %> (<%= tool.quantity %>)</p>
<% end %>

<p> <%= link_to "Create a new tool", new_tool_path %></p>

app/views/tools/new.html.erb
<h1>Create a new tool</h1>

<%= render partial: "form", locals: {user: @user, tool: @tool} %>

app/views/tools/show.html.erb
<h1><%= @tool.name %></h1>

<p>Price: $<%= @tool.price %></p>
<p>Quantity: <%= @tool.quantity %></p>

<%= link_to "Edit Tool", edit_user_tool_path(@user.id, @tool.id) %>
<%= link_to "Delete Tool", user_tool_path(user_id: @user.id, id: @tool.id), method: :delete %>

app/views/users/edit.html.erb
<h1>Edit user page</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit "Update My Account", method: :patch  %>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit "Create My Account"  %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %> show page</h1>

<h3><%= @user.username %>'s tools</h3>
<% @user.tools.each do |tool| %>
  <%= link_to tool.name, user_tool_path(@user.id, tool.id) %>
<% end %>

<% if @user.role == "admin" %>
  <%= link_to "Create A New Admin Tool", admin_tools_new_path %>
<% else %>
  <%= link_to "Create A New Tool", new_user_tool_path(@user.id) %>
<% end %>